---
grails:
    profile: rest-api
    codegen:
        defaultPackage: sx.server
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSources:
    dataSource:
        pooled: true
        dbCreate: update
        url: jdbc:mysql://localhost:3306/siipapx?autoReconnect=true
        driverClassName: com.mysql.jdbc.Driver
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        username: root
        password: sys
    importacion:
        pooled: true
        dbCreate: none
        url: jdbc:mysql://localhost/sw2?autoReconnect=true
        driverClassName: com.mysql.jdbc.Driver
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        username: root
        password: sys
environments:
    development:
        dataSources:
            dataSource:
                dbCreate: update
               #url: jdbc:mysql://localhost:3306/siipapx?autoReconnect=true
                url: jdbc:mysql://10.10.1.229/siipapx?autoReconnect=false
            importacion:
                dbCreate: none
                url: jdbc:mysql://10.10.1.228/produccion?autoReconnect=false
                properties:
                  maxActive: 3
                  maxIdle: 3
                  minIdle: 2
                  initialSize: 1
                  minEvictableIdleTimeMillis: 1800000
                  timeBetweenEvictionRunsMillis: 1800000
                  numTestsPerEvictionRun: 3
                  testOnBorrow: true
                  testWhileIdle: true
                  testOnReturn: true
                  maxWait: 10000
                  validationQuery: 'SELECT 1'
                  validationQueryTimeout: 3
                  validationInterval: 15000


    test:
        dataSources:
            dataSource:
                dbCreate: none
                pooled: true
                jmxExport: true
                driverClassName: org.h2.Driver
                url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
                username: sa
                password:
    production:
        dataSources:
            dataSource:
                dbCreate: none
                url: jdbc:mysql://10.10.1.229/siipapx?autoReconnect=false
                username: root
                password: sys
                properties:
                    maxActive: 10
                    maxIdle: 10
                    minIdle: 3
                    initialSize: 3
                    minEvictableIdleTimeMillis: 1800000
                    timeBetweenEvictionRunsMillis: 1800000
                    numTestsPerEvictionRun: 3
                    testOnBorrow: true
                    testWhileIdle: true
                    testOnReturn: true
                    maxWait: 10000
                    validationQuery: 'SELECT 1'
                    validationQueryTimeout: 3
                    validationInterval: 15000
---
server:
  port: 9090
  contextPath: /siipapx
---
grails:
    cors:
        enabled: true